MyField:

    Block:
        rigid: True
        size: root.width, 10
        pos: 0, 30

    Block:
        rigid: True
        size: root.width, 10
        pos: 0, root.height - 40

    Block:
        rigid: True
        size: 10, root.height
        pos: 30, 0

    Block:
        rigid: True
        size: 10, root.height
        pos: root.width - 40, 0

    Block:
        rigid: True
        size: root.width / 2, 10
        pos: (root.width - self.width) / 2, root.height / 2 - 5